{'name' :'Registro de notas ',
 'description': 'Registro de notas',
 'author' : 'Andre Zambrano Cueva',
 'depends' : ['base',
               'openeducat_core',
               ],
 'data' : [        
     'security/ir.model.access.csv',
     'views/asignaturas.xml',
     'views/notas_menu.xml',
     'views/anyaca.xml',
     'views/trimestre.xml',
     'views/unidad.xml',
     'views/criterios_libreta.xml',
     'views/nivel.xml',
     'views/meses_pension.xml',
     'views/alumnos.xml',
 ],
 'application' :True,
 'installable': True,
 }