{'name' :'Registro de notas ',
 'description': 'Registro de notas',
 'author' : 'Andre Zambrano Cueva',
 'deppends' : ['base','openeducat_activity',
               'openeducat_admission','openeducat_assignment',
               'openeducat_attendance','openeducat_classroom',
               'openeducat_core','openeducat_erp',
               'openeducat_exam','openeducat_facility',
               'openeducat_fees','openeducat_library',
               'openeducat_parent','openeducat_timetable',
               'web_openeducat','openeducat_erp-12.0',
               ],
 'data' : [        
     'security/ir.model.access.csv',
     'views/asignaturas_view.xml',
     'views/notas_menu.xml',
     'views/anyaca_view.xml',
     'views/trimestre_view.xml',
     'views/unidad_view.xml',
     'views/criterios_libreta_view.xml',

 ],
 'application' :True,
 'installable': True,
 }